version: '4.16.3'

services:
  dbaseJPA:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=NewsJPA
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
volumes:
  db:
    driver: local